name: mein_budget
description: Behalte deine Finanzen im Griff – Einnahmen, Ausgaben & Kredite einfach managen.
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  sqflite: ^2.3.0
  sqflite_common_ffi_web: ^0.4.1
  path_provider: ^2.1.1
  path: ^1.8.3
  intl: ^0.18.1
  uuid: ^4.2.1
  shared_preferences: ^2.2.2
  fl_chart: ^0.66.0
  local_auth: ^2.1.6
  csv: ^6.0.0
  share_plus: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1 # Paket hier hinzugefügt

flutter:
  uses-material-design: true
  assets:
    - assets/icon/icon_euro.png # Pfad korrigiert (ohne / am Anfang)

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon_euro.png"
  min_sdk_android: 21